FROM node:18-alpine

WORKDIR /app

# Install dependencies
COPY frontend/package*.json ./
RUN npm install

# Copy source
COPY frontend/ ./

# Expose port
EXPOSE 5173

# Run
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
